CE100 Algorithms and Programming II HW4: Algorithms.AES Class Reference
Algorithms.AES Class Reference
Provides methods for file transformation and encryption.
Static Public Member Functions
static void ConvertToBinary (string sourceFile, string destinationFile)
Converts a file to binary format.
static void TransformFile (string sourceFilePath, string destFilePath, int operation)
Transforms a file based on the specified operation.
static byte[] CalSha1 (byte[] data)
Calculates the SHA1 hash of the provided data.
static byte[] CalSha256 (byte[] data)
Calculates the SHA256 hash of the provided data.
Static Private Member Functions
static byte[] BufferSet (byte[] sha1Hash, byte[] fileData, byte[] sha256Hash)
Sets up the buffer with the specified data.
static byte[] EncData (byte[] data)
Encrypts the provided data using AES encryption algorithm.
static byte[] DecData (byte[] data)
Decrypts the provided data using AES encryption algorithm.
static bool CompHash (byte[] hash1, byte[] hash2)
Compares two hash values for equality.
Static Private Attributes
const int BytesBlockSize = 16
static readonly byte[] Key = Encoding.UTF8.GetBytes("mysecretkey12345")
Detailed Description
Provides methods for file transformation and encryption.
Member Function Documentation
BufferSet()
static byte [] Algorithms.AES.BufferSet (byte[] sha1Hash, byte[] fileData, byte[] sha256Hash) static private
Sets up the buffer with the specified data.
Parameters
sha1D The SHA1 hash of the file data.
fileData The file data.
sha256D The SHA256 hash of the file data.
Returns
The buffer containing the specified data.
References Algorithms.AES.BytesBlockSize.
Referenced by Algorithms.AES.TransformFile().
CalSha1()
static byte [] Algorithms.AES.CalSha1 (byte[] data) static
Calculates the SHA1 hash of the provided data.
Parameters
data The data to be hashed.
Returns
The SHA1 hash value.
Referenced by Algorithms.AES.TransformFile().
CalSha256()
static byte [] Algorithms.AES.CalSha256 (byte[] data) static
Calculates the SHA256 hash of the provided data.
Parameters
data The data to be hashed.
Returns
The SHA256 hash value.
Referenced by Algorithms.AES.TransformFile().
CompHash()
static bool Algorithms.AES.CompHash (byte[] hash1, byte[] hash2) static private
Compares two hash values for equality.
Parameters
hash1 The first hash value.
hash2 The second hash value.
Returns
True if the hash values are equal, otherwise false.
Referenced by Algorithms.AES.TransformFile().
ConvertToBinary()
static void Algorithms.AES.ConvertToBinary (string sourceFile, string destinationFile) static
Converts a file to binary format.
Parameters
sourceFile The path of the source file.
destinationFile The path of the destination file.
DecData()
static byte [] Algorithms.AES.DecData (byte[] data) static private
Decrypts the provided data using AES encryption algorithm.
Parameters
data The data to be decrypted.
Returns
The decrypted data.
References Algorithms.AES.BytesBlockSize, and Algorithms.AES.Key.
Referenced by Algorithms.AES.TransformFile().
EncData()
static byte [] Algorithms.AES.EncData (byte[] data) static private
Encrypts the provided data using AES encryption algorithm.
Parameters
data The data to be encrypted.
Returns
The encrypted data.
References Algorithms.AES.BytesBlockSize, and Algorithms.AES.Key.
Referenced by Algorithms.AES.TransformFile().
TransformFile()
static void Algorithms.AES.TransformFile (string sourceFilePath, string destFilePath, int operation) static
Transforms a file based on the specified operation.
Parameters
sourceFilePath The path of the source file.
destFilePath The path of the destination file.
operation The operation to be performed (0 for decryption, 1 for encryption).
References Algorithms.AES.BufferSet(), Algorithms.AES.CalSha1(), Algorithms.AES.CalSha256(), Algorithms.AES.CompHash(), Algorithms.AES.DecData(), and Algorithms.AES.EncData().
Member Data Documentation
BytesBlockSize
const int Algorithms.AES.BytesBlockSize = 16 static private
Referenced by Algorithms.AES.BufferSet(), Algorithms.AES.DecData(), and Algorithms.AES.EncData().
Key
readonly byte [] Algorithms.AES.Key = Encoding.UTF8.GetBytes("mysecretkey12345") static private
Referenced by Algorithms.AES.DecData(), and Algorithms.AES.EncData().
The documentation for this class was generated from the following file:
CryptoLibrary.csproj/Algorithms.cs